apiVersion: v1

kind: ConfigMap


metadata:

  name: {{ include "persona-rest.fullname" . }}-config

  labels:

    {{- include "persona-rest.labels" . | nindent 4 }}


data:

  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
