apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "persona-rest.fullname" . }}-mysql-data

spec:

  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:

    requests:

      storage: 5Gi
