apiVersion: apps/v1

kind: Deployment

metadata:

  name: {{ include "persona-rest.fullname" . }}-mysql

  labels:

    app: mysql


spec:

  replicas: 1


  selector:

    matchLabels:

      app: mysql


  template:

    metadata:

      labels:

        app: mysql


    spec:

      containers:

        - name: mysql

          image: mysql:8.0


          imagePullPolicy: IfNotPresent


          ports:

            - containerPort: 3306


          env:

            - name: MYSQL_ROOT_PASSWORD

              valueFrom:

                secretKeyRef:

                  name: {{ include "persona-rest.fullname" . }}

                  key: rootPassword


            - name: MYSQL_DATABASE

              valueFrom:

                secretKeyRef:

                  name: {{ include "persona-rest.fullname" . }}

                  key: database


            - name: MYSQL_USER

              valueFrom:

                secretKeyRef:

                  name: {{ include "persona-rest.fullname" . }}

                  key: username


            - name: MYSQL_PASSWORD

              valueFrom:

                secretKeyRef:

                  name: {{ include "persona-rest.fullname" . }}

                  key: password


          volumeMounts:

            - name: mysql-data

              mountPath: /var/lib/mysql


      volumes:

        - name: mysql-data

          persistentVolumeClaim:

            claimName: {{ include "persona-rest.fullname" . }}-mysql-data
