apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret

type: Opaque

stringData:

  MYSQL_ROOT_PASSWORD: rootpassword

  MYSQL_DATABASE: persona

  MYSQL_USER: persona

  MYSQL_PASSWORD: password
