apiVersion: v1
kind: Secret

metadata:
  name: {{ include "persona-rest.fullname" . }}

type: Opaque

stringData:

  username: persona

  password: password

  rootPassword: rootpassword

  database: persona
